--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.8) ~  Much Love, Ferib 

]]--

local v0=loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wizard"))();local v1=v0:NewWindow("Race by rdx222");local v2=v1:NewSection("Main");local v3=false;v2:CreateToggle("Auto Wins",function(v8) local v9=0 -0 ;while true do if (v9==(1065 -(68 + 997))) then v3=v8;while v3 do local v15=TweenInfo.new(1272 -(226 + 1044) );local v16={CFrame=CFrame.new( -(17425984 -13424062),2,117 -(32 + 85) )};local v17=game:GetService("TweenService"):Create(game.Players.LocalPlayer.Character.HumanoidRootPart,v15,v16);v17:Play();wait(5 + 0 );end break;end end end);local v4=false;v2:CreateToggle("Auto Click",function(v10) local v11=0;while true do if (v11==(0 + 0)) then v4=v10;while v4 do local v18=957 -(892 + 65) ;while true do if (v18==1) then game:GetService("ReplicatedStorage").Packages.Knit.Services.ClickService.RF.Click:InvokeServer();wait(1);break;end if (v18==(0 -0)) then game:GetService("ReplicatedStorage").Packages.Knit.Services.ClickService.RF.Click:InvokeServer();wait(0.5 -0 );v18=1 -0 ;end end end break;end end end);local v5=false;v2:CreateToggle("Auto Hatch (level 1)",function(v12) local v13=350 -(87 + 263) ;while true do if ((180 -(67 + 113))==v13) then v5=v12;while v5 do local v19=0;local v20;while true do if ((0 + 0)==v19) then v20={[2 -1 ]="Starter01",[2 + 0 ]="1",[11 -8 ]={}};game:GetService("ReplicatedStorage").Packages.Knit.Services.EggService.RF.Open:InvokeServer(unpack(v20));v19=953 -(802 + 150) ;end if (v19==1) then wait(2 -1 );break;end end end break;end end end);local v6=false;v2:CreateToggle("Auto Rebirth",function(v14) v6=v14;while v6 do game:GetService("ReplicatedStorage").Packages.Knit.Services.RebirthService.RF.Rebirth:InvokeServer();wait(1 -0 );end end);local v7=v1:NewSection("Script Bye Rdx222");
